
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// AI配置
    /// </summary>
    [Config]
    public partial class AIConfigCategory : Singleton<AIConfigCategory>
    {
        private readonly Dictionary<int, AIConfig> _dataMap;
        private readonly List<AIConfig> _dataList;

        public AIConfigCategory()
        {
            throw new NotImplementedException();
        }

        public AIConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, AIConfig>();
            _dataList = new List<AIConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                AIConfig _v;
                _v = AIConfig.DeserializeAIConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public void ForEach(Action<AIConfig> action)
        {
            foreach (var config in _dataMap.Values)
            {
                action.Invoke(config);
            }
        }

        public void ForEach(Func<AIConfig, bool> action)
        {
            foreach (var config in _dataMap.Values)
            {
                if (!action.Invoke(config))
                {
                    break;
                }
            }
        }

        public AIConfig Query(Func<AIConfig, bool> action)
        {
            foreach (var config in _dataMap.Values)
            {
                if (action.Invoke(config))
                {
                    return config;
                }
            }

            return null;
        }

        public List<AIConfig> QueryAll(Func<AIConfig, bool> action)
        {
            List<AIConfig> result = new();
            foreach (var config in _dataMap.Values)
            {
                if (action.Invoke(config))
                {
                    result.Add(config);
                }
            }

            return result;
        }

        public Dictionary<int, AIConfig> DataMap => _dataMap;
        public List<AIConfig> DataList => _dataList;

        public Dictionary<int, AIConfig> GetAll() => _dataMap;
        public AIConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public AIConfig Get(int key) => _dataMap[key];
        public AIConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
