
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class StartProcessConfigCategory : Singleton<StartProcessConfigCategory>
    {
        private readonly Dictionary<int, StartProcessConfig> _dataMap;
        private readonly List<StartProcessConfig> _dataList;

        public StartProcessConfigCategory()
        {
            throw new NotImplementedException();
        }

        public StartProcessConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, StartProcessConfig>();
            _dataList = new List<StartProcessConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                StartProcessConfig _v;
                _v = StartProcessConfig.DeserializeStartProcessConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public void ForEach(Action<StartProcessConfig> action)
        {
            foreach (var config in _dataMap.Values)
            {
                action.Invoke(config);
            }
        }

        public void ForEach(Func<StartProcessConfig, bool> action)
        {
            foreach (var config in _dataMap.Values)
            {
                if (!action.Invoke(config))
                {
                    break;
                }
            }
        }

        public StartProcessConfig Query(Func<StartProcessConfig, bool> action)
        {
            foreach (var config in _dataMap.Values)
            {
                if (action.Invoke(config))
                {
                    return config;
                }
            }

            return null;
        }

        public List<StartProcessConfig> QueryAll(Func<StartProcessConfig, bool> action)
        {
            List<StartProcessConfig> result = new();
            foreach (var config in _dataMap.Values)
            {
                if (action.Invoke(config))
                {
                    result.Add(config);
                }
            }

            return result;
        }

        public Dictionary<int, StartProcessConfig> DataMap => _dataMap;
        public List<StartProcessConfig> DataList => _dataList;

        public Dictionary<int, StartProcessConfig> GetAll() => _dataMap;
        public StartProcessConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public StartProcessConfig Get(int key) => _dataMap[key];
        public StartProcessConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
