
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class StartZoneConfigCategory : Singleton<StartZoneConfigCategory>
    {
        private readonly Dictionary<int, StartZoneConfig> _dataMap;
        private readonly List<StartZoneConfig> _dataList;

        public StartZoneConfigCategory()
        {
            throw new NotImplementedException();
        }

        public StartZoneConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, StartZoneConfig>();
            _dataList = new List<StartZoneConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                StartZoneConfig _v;
                _v = StartZoneConfig.DeserializeStartZoneConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public void ForEach(Action<StartZoneConfig> action)
        {
            foreach (var config in _dataMap.Values)
            {
                action.Invoke(config);
            }
        }

        public void ForEach(Func<StartZoneConfig, bool> action)
        {
            foreach (var config in _dataMap.Values)
            {
                if (!action.Invoke(config))
                {
                    break;
                }
            }
        }

        public StartZoneConfig Query(Func<StartZoneConfig, bool> action)
        {
            foreach (var config in _dataMap.Values)
            {
                if (action.Invoke(config))
                {
                    return config;
                }
            }

            return null;
        }

        public List<StartZoneConfig> QueryAll(Func<StartZoneConfig, bool> action)
        {
            List<StartZoneConfig> result = new();
            foreach (var config in _dataMap.Values)
            {
                if (action.Invoke(config))
                {
                    result.Add(config);
                }
            }

            return result;
        }

        public Dictionary<int, StartZoneConfig> DataMap => _dataMap;
        public List<StartZoneConfig> DataList => _dataList;

        public Dictionary<int, StartZoneConfig> GetAll() => _dataMap;
        public StartZoneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public StartZoneConfig Get(int key) => _dataMap[key];
        public StartZoneConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
