
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 在luban用于管理各个配置文件的脚本，在ET中我们统一使用ConfigComponent管理，所以就没有生成模板
